# Generated by Django 4.1.7 on 2023-05-21 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='fk_product',
        ),
        migrations.AddField(
            model_name='cart',
            name='fk_product',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
            preserve_default=False,
        ),
    ]
